src/DF/CommentBundle/Entity/Comment.php
<?php

namespace DF\CommentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Comment as BaseComment;
use FOS\CommentBundle\Model\SignedCommentInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Config\Definition\IntegerNode;
use PA\CommentairesBundle\Controller\PublicController;

/**
 * @ORM\Table(name="comment")
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Comment extends BaseComment  implements SignedCommentInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\generatedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Thread of this comment
     *
     * @var Thread
     * @ORM\ManyToOne(targetEntity="DF\CommentBundle\Entity\Thread")
     */
    protected $thread;
    
    /**
     * Author of the comment
     *
     * @ORM\ManyToOne(targetEntity="DF\UserBundle\Entity\User")
     * @var User
     */
    protected $author;
    
    public function setAuthor(UserInterface $author)
    {
        $this->author = $author;
    }
    
    public function getAuthor()
    {
        return $this->author;
    }
    
    public function getAuthorName()
    {
        if (null === $this->getAuthor()) {
            return 'Anonymous';
        }
    
        return $this->getAuthor();
    }  

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
}

src/DF/CommentBundle/Entity/Thread.php
<?php
namespace DF\CommentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Thread as BaseThread;

/**
 * @ORM\Table(name="Thread")
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Thread extends BaseThread
{
    /**
     * @var string $id
     *
     * @ORM\Id
     * @ORM\Column(type="string")
     */
    protected $id;
}

src/DF/CommentBundle/Controller/PublicController.php
<?php 

namespace DF\CommentBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Yaml\Parser;
use Symfony\Component\Yaml\Exception\ParseException;
use DF\CommentBundle\Entity\Thread;

class PublicController extends Controller 
{
	
	public function getNumberCommentAction($id)
	{
		$thread = new Thread();
		$thread = $this
			->getDoctrine()
			->getManager()
			->getRepository('DFCommentBundle:Thread')
			->find($id);
		
		if(!$thread)
			return new Response(0);
		else		
			return new Response($thread->getNumComments());
	}
}

src/DF/CommentBundle/Controller/ThreadController.php
<?php 

namespace DF\CommentBundle\Controller;

use FOS\CommentBundle\Controller\ThreadController as Controller;
use FOS\CommentBundle\Model\ThreadInterface;
use Symfony\Bundle\FrameworkBundle\Templating\TemplateReference;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use JMS\SecurityExtraBundle\Annotation\Secure;

class ThreadController extends Controller 
{
}

src/DF/CommentBundle/Resources/views/Thread/async.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<div id="fos_comment_thread"></div>

{% javascripts '@FOSCommentBundle/Resources/assets/js/comments.js' %}
<script type="text/javascript">
// thread id
var fos_comment_thread_id = '{{ id }}';

// api base url to use for initial requests
var fos_comment_thread_api_base_url = '{{ path('fos_comment_get_threads') }}';

// Snippet for asynchronously loading the comments
(function() {
    var fos_comment_script = document.createElement('script');
    fos_comment_script.async = true;
    fos_comment_script.src = '{{ asset_url }}';
    fos_comment_script.type = 'text/javascript';

    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(fos_comment_script);
})();
</script>
{% endjavascripts %}

{% stylesheets '@DFCommentBundle/Resources/public/css/comment.css' %}
	<link href="{{ asset_url }}" rel="stylesheet" />
{% endstylesheets %}

{% javascripts '@DFCommentBundle/Resources/public/js/comment.js' %}
	<script src="{{ asset_url }}"></script>
{% endjavascripts %}

src/DF/CommentBundle/Resources/views/Thread/comment.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% set view = view|default('tree') %}
{% set depth = depth|default(0) %}

{% include "FOSCommentBundle:Thread:comment_content.html.twig" %}

src/DF/CommentBundle/Resources/views/Thread/comment_content.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% block fos_comment_comment %}
<div id="fos_comment_{{ comment.id }}" class="fos_comment_comment_show fos_comment_comment_depth_{{ depth }}" {% if parent is defined %}data-parent="{{ parent.id }}"{% endif %}>
    <div class="fos_comment_comment_metas">
        <a href="">
        	<img src="{{ asset('bundles/dfcomment/images/001.png') }}" alt="" />
        </a>
    </div>
    <header>
    	{% block fos_comment_comment_metas %}
            {% block fos_comment_comment_metas_authorline %}
                <span class="fos_comment_comment_authorname">
                        {{ comment.authorName }}
                </span>
                <span class="bulle">•</span>
                <span class="fos_comment_comment_createdAt">
               		le {{ comment.createdAt|date('d/m/Y à H:i') }}
	            </span>
            {% endblock fos_comment_comment_metas_authorline %}
        {% endblock fos_comment_comment_metas %}
    </header>	
    <div id="fos_comment_comment_body_{{ comment.id }}" class="fos_comment_comment_body">
        {% block fos_comment_comment_body %}
            {% if comment is fos_comment_in_state(constant('FOS\\CommentBundle\\Model\\CommentInterface::STATE_DELETED')) %}
                {% trans from 'FOSCommentBundle' %}fos_comment_comment_deleted{% endtrans %}
            {% else %}
                {% if comment is fos_comment_raw %}
                    {{ comment.rawBody | raw }}
                {% else %}
                    {{ comment.body | nl2br }}
                {% endif %}
            {% endif %}
        {% endblock fos_comment_comment_body %}
        <footer>
            {% block fos_comment_comment_metas_edit %}
                {% if fos_comment_can_edit_comment(comment) %}
                	<p data-container="#fos_comment_comment_body_{{ comment.id }}" data-url="{{ url("fos_comment_edit_thread_comment", {"id": comment.thread.id, "commentId": comment.id}) }}" class="fos_comment_comment_edit_show_form bt_com">Modifier</p>
                {% endif %}
            {% endblock fos_comment_comment_metas_edit %}
            {% if fos_comment_can_comment(comment) %}
            	{% block fos_comment_comment_reply %}
                	<p data-url="{{ url('fos_comment_new_thread_comments', {"id": comment.thread.id}) }}" data-name="{{ comment.authorName }}" data-parent-id="{{ comment.id }}" class="fos_comment_comment_reply_show_form bt_com">{% trans from 'FOSCommentBundle' %}fos_comment_comment_show_reply{% endtrans %}</p>
                {% endblock fos_comment_comment_reply %}
            {% endif %}
        </footer>
    </div>
    {% block fos_comment_comment_children %}
        {% if view is not sameas('flat') %}
            

            <div class="fos_comment_comment_replies">

                {% if children is defined %}
                    {% include "FOSCommentBundle:Thread:comments.html.twig" with { "comments": children, "depth": depth + 1, "parent": comment, "view": view } %}
                {% endif %}

            </div>
        {% elseif view is sameas('flat') and children is defined %}
            {% include "FOSCommentBundle:Thread:comments.html.twig" with { "comments": children, "depth": depth + 1, "parent": comment, "view": view } %}
        {% endif %}
    {% endblock fos_comment_comment_children %}
</div>
{% endblock fos_comment_comment %}

src/DF/CommentBundle/Resources/views/Thread/comment_edit.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<div class="fos_comment_comment_form_holder">
    <form class="fos_comment_comment_edit_form" action="{{ url('fos_comment_put_thread_comments', {'id': comment.thread.id, 'commentId': comment.id}) }}" method="POST">

        {% block fos_comment_form_fields %}
            {{ form_errors(form) }}
            {{ form_errors(form.body) }}
            <div class="form_textarea">
            	{{ form_widget(form.body) }}
            </div>
            {{ form_widget(form._token) }}
        {% endblock %}

        <div class="fos_comment_submit">
            <input type="button" class="fos_comment_comment_edit_cancel" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_edit_cancel{% endtrans %}" />
            {% block fos_comment_form_submit %}
                <input type="submit" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_edit_submit{% endtrans %}" />
            {% endblock %}
        </div>

        <input type="hidden" name="_method" value="PUT">

    </form>
</div>
<script type="text/javascript">
	$(modifTextarea);
</script>

src/DF/CommentBundle/Resources/views/Thread/comment_new.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% include "FOSCommentBundle:Thread:comment_new_content.html.twig" %}

src/DF/CommentBundle/Resources/views/Thread/comment_new_content.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% set first = first|default(false) %}

{% set url_parameters = {'id': id } %}
{% if parent is not null %}
    {% set url_parameters = url_parameters|merge({'parentId': parent.id}) %}
{% endif %}

{% block fos_comment_comment_form_holder %}
    <div class="fos_comment_comment_form_holder">
        {% block fos_comment_comment_new_form %}
            <form class="fos_comment_comment_new_form" action="{{ url('fos_comment_post_thread_comments', url_parameters) }}" data-parent="{{ parent.id|default() }}" method="POST">

                {% block fos_comment_form_fields %}
                    <div class="fos_comment_form_errors">
                    {{ form_errors(form) }}
                    {{ form_errors(form.body) }}
                    </div>
                    <div class="form_textarea">
                    	{{ form_widget(form.body) }}
                    </div>

                    {{ form_rest(form) }}
                {% endblock %}

                <div class="fos_comment_submit">
                    {% block fos_comment_form_submit %}
                        {% if parent is not null %}
                            <input type="button" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_reply_cancel{% endtrans %}" class="fos_comment_comment_reply_cancel" />
                        {% endif %}
                        <input type="submit" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_new_submit{% endtrans %}" />
                    {% endblock %}
                </div>
            </form>
        {% endblock fos_comment_comment_new_form %}

    </div>
{% endblock fos_comment_comment_form_holder %}
<script type="text/javascript">
	$(modifTextarea);
</script>

src/DF/CommentBundle/Resources/views/Thread/comment_remove.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<div class="fos_comment_delete_form_holder">
    <form class="fos_comment_delete_form" action="{{ url('fos_comment_patch_thread_comment_state', {'id': id, 'commentId': commentId}) }}" data-fos-comment-thread-id="{{ id }}" method="POST">

        {% block fos_comment_form_fields %}
            {{ form_errors(form) }}

            {{ form_rest(form) }}
        {% endblock %}

        <input type="hidden" name="_method" value="patch" />

        <div class="fos_comment_submit">
            {% block fos_comment_form_submit %}
                <input type="submit" value="{{ 'fos_comment_comment_delete' | trans({}, 'FOSCommentBundle') }}" />
            {% endblock %}
        </div>

    </form>
</div>

src/DF/CommentBundle/Resources/views/Thread/comment_votes.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% trans from 'FOSCommentBundle' %}fos_comment_comment_vote_score{% endtrans %} {{ commentScore }}

src/DF/CommentBundle/Resources/views/Thread/commentable.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<div class="fos_comment_commentable_form_holder">
    <form class="fos_comment_commentable_form" action="{{ url('fos_comment_patch_thread_commentable', {'id': id}) }}" data-fos-comment-thread-id="{{ id }}" method="POST">

        {% block fos_comment_form_fields %}
            {{ form_errors(form) }}

            {{ form_errors(form.isCommentable) }}
            {{ form_widget(form.isCommentable) }}

            {{ form_rest(form) }}
        {% endblock %}

        <input type="hidden" name="_method" value="patch" />

        <div class="fos_comment_submit">
            {% block fos_comment_form_submit %}
                <input type="submit" value="{{ (isCommentable ? 'fos_comment_thread_open' : 'fos_comment_thread_close') | trans({}, 'FOSCommentBundle') }}" />
            {% endblock %}
        </div>

    </form>
</div>

src/DF/CommentBundle/Resources/views/Thread/comments.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

{% set depth = depth|default(0) %}
{% set view = view|default('tree') %}

{% if depth == 0 %}
	{% set count = thread.numComments %}
    <h3>{% transchoice count with {'%count%': count} from "FOSCommentBundle" %}fos_comment_thread_comment_count{% endtranschoice %}</h3>
    {% if fos_comment_can_comment_thread(thread) %}
        {% render url("fos_comment_new_thread_comments", {"id": thread.id}) %}
    {% endif %}
{% endif %}

{% for commentinfo in comments %}
    {% include "FOSCommentBundle:Thread:comment.html.twig" with { "children": commentinfo.children, "comment": commentinfo.comment, "depth": depth, "view": view } %}
{% endfor %}

src/DF/CommentBundle/Resources/views/Thread/errors.html.twig
<ul>
{% for error in errors %}
    <li>{{ error }}</li>
{% endfor%}
</ul>

src/DF/CommentBundle/Resources/views/Thread/new.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<form class="fos_comment_comment_form" action="{{ url('fos_comment_post_threads') }}" method="POST">

    {% block fos_comment_form_fields %}
        {{ form_errors(form) }}
        {{ form_errors(form.id) }}
        {{ form_widget(form.id) }}
        {{ form_errors(form.permalink) }}
        {{ form_widget(form.permalink) }}

        {{ form_rest(form) }}
    {% endblock %}

    <div class="fos_comment_submit">
        {% block fos_comment_form_submit %}
            <input type="submit" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_new_submit{% endtrans %}" />
        {% endblock %}
    </div>

</form>

src/DF/CommentBundle/Resources/views/Thread/thread_xml_feed.rss.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<feed xmlns="http://www.w3.org/2005/Atom">
    <title>{{ thread.id }}</title>
    <id>{{ thread.id }}</id>
    <link href="{{ thread.permalink }}" rel="alternate" />
    <updated>{{ thread.lastCommentAt|date("c") }}</updated>
{% for commentinfo in comments %}
    <entry>
        <title>By {{ commentinfo.comment.authorName }} on {{ commentinfo.comment.createdAt|date }}</title>
        <author>
            <name>{{ commentinfo.comment.authorName }}</name>
        </author>
        <updated>{{ commentinfo.comment.createdAt|date("c") }}</updated>
        <link rel="alternate">{{ thread.permalink }}#{{ commentinfo.comment.id }}</link>
        <summary>{{ commentinfo.comment.body }}</summary>
    </entry>
{% endfor %}
</feed>

src/DF/CommentBundle/Resources/views/Thread/vote_new.html.twig
{#

 This file is part of the FOSCommentBundle package.

 (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>

 This source file is subject to the MIT license that is bundled
 with this source code in the file LICENSE.

#}

<div class="fos_comment_vote_form_holder">
    <form class="fos_comment_vote_form" action="{{ url('fos_comment_post_thread_comment_votes', {'id': id, 'commentId': commentId}) }}" data-score-holder="fos_comment_score_{{ commentId }}" method="POST">

        {% block fos_comment_form_fields %}
            {{ form_errors(form) }}
            {{ form_errors(form.value) }}
            {{ form_widget(form.value) }}

            {{ form_rest(form) }}
        {% endblock %}

        <div class="fos_comment_submit">
            {% block fos_comment_form_submit %}
                <input type="submit" />
            {% endblock %}
        </div>

    </form>
</div>